---
title: "A4 Hierarchical"
author: "R"
date: "3/24/2020"
output: html_document
---
```{r}
library(factoextra)
library(cluster)
library(dplyr)
library(ggplot2)
library(data.table)
library(tidyverse)
library(FNN)
```
# Hierarchical Clustering

```{r}
lung_cancer<- read.csv("E:/Big Data II/A4 Clustering/Air Quality-Lung Cancer Data.csv")
# Considering the high collinearity between some variables, we drop some variables to avoid that some variables get a higher weight than others
lung_cancer_data<- lung_cancer[,c(1,5,7,8,9,15,16,17,18,19,20,21,23)]

# Normalized distance:
lung_cancer_sc<- scale(lung_cancer_data[,2:13])

# Change the FIPS_code to row names 
row.names(lung_cancer_sc) <- lung_cancer_data[ ,1]

head(lung_cancer_sc)

# Try different methods for computing distance
lungcancer_dist1<- dist(lung_cancer_sc, method = "euclidean")
lungcancer_dist2<- dist(lung_cancer_sc, method = "maximum")
lungcancer_dist3<- dist(lung_cancer_sc, method = "manhattan")
lungcancer_dist4<- dist(lung_cancer_sc, method = "canberra")
lungcancer_dist5<- dist(lung_cancer_sc, method = "binary")
lungcancer_dist6<- dist(lung_cancer_sc, method = "minkowski")

lungcancer_hc1<- hclust(lungcancer_dist1, method = "single")
lungcancer_hc2<- hclust(lungcancer_dist1, method = "complete")
lungcancer_hc3<- hclust(lungcancer_dist1, method = "average")
lungcancer_hc4<- hclust(lungcancer_dist1, method = "median")
lungcancer_hc5<- hclust(lungcancer_dist1, method = "centroid")
lungcancer_hc6<- hclust(lungcancer_dist1, method = "ward.D")

plot(lungcancer_hc1, hang = -1, ann = FALSE) 
plot(lungcancer_hc2, hang = -1, ann = FALSE) 
plot(lungcancer_hc3, hang = -1, ann = FALSE) 
plot(lungcancer_hc4, hang = -1, ann = FALSE) 
plot(lungcancer_hc5, hang = -1, ann = FALSE) 
plot(lungcancer_hc6, hang = -1, ann = FALSE) 
# The plot using "ward.D" method looks the best.

```

### Determining Optimal Clusters
```{r cars}
# Perform Average Silhouette Method
fviz_nbclust(lung_cancer_sc, FUN = hcut, method = "silhouette")

# Perform Gap Statistic Method
mydist <- function(x) dist(x, method = "euclidean")
mycluster <- function(x, k) list(cluster=cutree(hclust(mydist(x), method = "ward.D"),k=k))
myclusGap <- clusGap(lung_cancer_sc,FUN = mycluster, K.max = 13, B = 50)
fviz_gap_stat(myclusGap)

# Considering the number of clusters and the distribution, we choose k equal to 3.

```

```{r}
lungcancer_cut <- cutree(lungcancer_hc6, k = 3) #ward.D
```


```{r}
# Elbow method
fviz_nbclust(lung_cancer_sc, FUN = hcut, method = "wss")

```

```{r}
# Gap Statistic Method
gap_stat<- clusGap(lung_cancer_sc,FUN= hcut, K.max = 20, B = 50)
fviz_gap_stat(gap_stat)
```
### Visualization
```{r}
#dendrogram
hcd <- as.dendrogram(lungcancer_hc6)
nodePar <- list(lab.cex = 0.001, pch = c(NA, 19), 
                cex = 0.001, col = "blue")
plot(hcd, ylab = "Height", nodePar = nodePar, leaflab = "none")
rect.hclust(lungcancer_hc6, k=3, border = 2:4)

# Zoom in to the first dendrogram
plot(hcd, xlim = c(1,14), ylim = c(1,5))
```

```{r pressure, echo=FALSE}
# heatmap
heatmap(as.matrix(lung_cancer_sc), Colv = NA, hclustfun = hclust, main = "heatmap")
# Visualize the result in a scatter plot
fviz_cluster(list(data = lung_cancer_sc, cluster = lungcancer_cut))
```

```{r}
# Analyze the trend between lung cancer Mortality and PM2.5 from the data cluster-wise 
seeds_df_cl <- mutate(lung_cancer_data, cluster = lungcancer_cut)
ggplot(seeds_df_cl, aes(x=PM2.5, y = Land_EQI, color = factor(cluster))) + geom_point()


```
### Add the new clustering result to the original dataset 
```{r}
Hie_Cluster = data.frame(lungcancer_cut)
lung_Hie <- cbind(lung_cancer,Hie_Cluster)
head(lung_Hie)

#Export the new dataset
write.csv(lung_Hie, "E:/Big Data II/A4 Clustering/lungcancer Hiecluster.csv")

```

# Kmeans Clustering

prepare data
```{r,warning=FALSE, message=FALSE}
lungcancer <- read.csv(file = 'Air Quality_Lung Cancer Data.csv')
lung = lungcancer[,c(1,4,5,7,8,9,15,16,17,18,19,20,21,22,23)]
# nomalize data
row.names(lung) <- lung[,1]
lung <-lung[,-1]
lung.norm <- sapply(lung, scale)
lung.norm = as.data.frame(lung.norm)
```

### clustering
```{r,warning=FALSE, message=FALSE}
ratio_ss <- rep(0,7)
for (k in 1:7) {
  lung_km <- kmeans(lung.norm$Lung.Cancer, k, nstart = 20)
  ratio_ss[k] <- lung_km$tot.withinss
  
}
plot(ratio_ss, type = 'b', xlab = 'k')
# dendrogram
hc <- hclust(dist(lung.norm), "ward.D")
plot(hc) 
rect.hclust(hc, k = 4, border="red") 
grid()
memb <- cutree(hc, k = 4)
# from plot, we choose k=4
lungkm <- kmeans(lung.norm, 4)
lungkm$centers
lungkm$size
dist(lungkm$centers)
# line plots
plot(c(0), xaxt = 'n', ylab = "", type = "l", 
     ylim = c(min(lungkm$centers), max(lungkm$centers)), xlim = c(0, 13))
axis(1, at = c(1:13), labels = names(lung[-1]))
for (i in c(1:4))
  lines(lungkm$centers[i,], lty = i, lwd = 2, col = switch(i,  "red", "black",
                                                       "green", "purple"))
text(x = 0.5, y = lungkm$centers[, 1], labels = paste("Cluster", c(1:4)))
grid()
#cluster
fviz_cluster(lungkm, data = lung.norm)
#heatmap
heatmap(as.matrix(lung.norm)[order(lungkm$cluster),], Colv = NA, hclustfun = hclust)
# scatter plot
clusplot(lung.norm, lungkm$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
with(lung.norm, pairs(lung.norm[,c(1:4)], col=c(1:4)[lungkm$cluster])) 
lung.norm %>%
  as_tibble() %>%
  mutate(cluster = lungkm$cluster) %>%
  ggplot(aes(Lung.Cancer,PM2.5, color = factor(cluster))) +
  geom_point()
```

```{r,warning=FALSE, message=FALSE}
#Copy the cluster data back to your original data as a new predictor: KMeansCluster
KMeansCluster = as.factor(lungkm$cluster)
lungkmeans <- cbind(lungcancer,KMeansCluster)
head(lungkmeans)
write.csv(lungkmeans, "lungcancerkmeans", sep="\t", row.names=FALSE, col.names=FALSE)
```
